org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=false
# Permite compilar com compileSdk 36 no AGP 8.5.2 (testado até 34)
android.suppressUnsupportedCompileSdk=34,35,36

kotlin.code.style=official
